  - name: Update packages
    apt:
      update_cache: yes
    become: yes

  - name: Install Dependencies
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - curl
      - containerd
    become: yes

  - name: Add GPG key for Kubernetes
    shell: |
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    become: yes

  - name: Add Kubernetes apt repository
    shell: |
      sudo echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
    become: yes

  - name: Update package cache after adding Kubernetes repo
    apt:
      update_cache: yes
    become: yes

  - name: Install Kubernetes components
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - kubelet
      - kubeadm
      - kubectl
    become: yes

  - name: Disable swap
    shell: |
      swapoff -a
      sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    become: yes

  - name: Load kernel modules
    shell: |
      modprobe overlay
      modprobe br_netfilter
    become: yes

  - name: Set required sysctl parameters
    shell: |
      cat <<EOF | tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      EOF
    become: yes

  - name: Apply sysctl parameters
    command: sysctl --system
    become: yes

  - name: Initialize the Kubernetes cluster (run only on master node)
    command: kubeadm init --pod-network-cidr=10.244.0.0/16
    become: yes

  - name: Create .kube directory
    file:
      path: "/home/ubuntu/.kube"
      state: directory

  - name: Copy admin.conf to kube config
    command: sudo cp -i  /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
    become: true
    delegate_to: localhost

  - name: Change the ownership of kube config
    command: sudo chown ubuntu:ubuntu /home/ubuntu/.kube/config

  - name: Pause for 20 secs
    pause:
      seconds: 20

  - name: Get control-plane node name
    command: kubectl get nodes --selector=node-role.kubernetes.io/control-plane --no-headers -o custom-columns=":metadata.name"
    register: control_plane_node

  - name: Remove taint from the control-plane node
    command: kubectl taint node {{ control_plane_node.stdout.strip() }} node-role.kubernetes.io/control-plane:NoSchedule-

  - name: Install Calico CNI
    command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
    notify: Pause for 10 secs
